//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallAttendanceAPIService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header_DiemDanh_NangSuat_LaoDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Header_DiemDanh_NangSuat_LaoDong()
        {
            this.DiemDanh_NangSuatLaoDong = new HashSet<DiemDanh_NangSuatLaoDong>();
            this.DiemDanh_NangSuatLaoDong1 = new HashSet<DiemDanh_NangSuatLaoDong>();
        }
    
        public int HeaderID { get; set; }
        public int Ca { get; set; }
        public System.DateTime NgayDiemDanh { get; set; }
        public System.DateTime FetchDataTime { get; set; }
        public bool Status { get; set; }
        public string Message { get; set; }
        public string VERSION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemDanh_NangSuatLaoDong> DiemDanh_NangSuatLaoDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemDanh_NangSuatLaoDong> DiemDanh_NangSuatLaoDong1 { get; set; }
        public virtual Header_DiemDanh_NangSuat_LaoDong_Detail Header_DiemDanh_NangSuat_LaoDong_Detail { get; set; }
    }
}
